build: resolve -Wreturn-type warnings
Functions without return can produce unpredictable behavior,
and it goes without saying that is bad.
openSUSE has added -Werror=return-type distro-wide, so it is
perhaps fair to do the same here.

fmt/iti.c: In function ‘load_it_instrument_old’:
fmt/iti.c:157:1: error: control reaches end of non-void function [-Werror=return-type]
fmt/iti.c: In function ‘load_it_instrument’:
fmt/iti.c:207:1: error: control reaches end of non-void function [-Werror=return-type]

on Wii platform, there are some more:

../schism/controller.c: In function 'game_controller_insert':
../schism/controller.c:50:1: error: no return statement in function returning non-void [-Werror=return-type]
../schism/controller.c: In function 'controller_quit':
../schism/controller.c:112:1: error: control reaches end of non-void function [-Werror=return-type]